[project]
name = "api-amazon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.10.1",
    "fastapi[standard]>=0.121.1",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
]
